### ISSUE TITLE
Conversation to Core ML Failed

### ISSUE THREAD

**Issue by jasmin-techie** [fritzlabs/fritz-models#41]
I am trying to create custom coreml model but it fails in Core ML conversation step. please check screenshot.

![Screenshot](https://user-images.githubusercontent.com/28618551/59108995-cfa06200-8959-11e9-9149-ec9b59985fda.png)

**Comment by jamesonthecrow** [comment]
Thanks for bringing this to our attention. It appears the latest release of coremltools has broken some of the conversion. You can fix the training notebook by changing the `pip install` command at the very top to:

`!pip install git+https://github.com/apple/coremltools.git@v2.1`

I've updated the master template so new notebooks should be fine.
