### ISSUE TITLE
tflite interpreter in android gives error when ran

### ISSUE THREAD

**Issue by Jayanth-L** [fritzlabs/fritz-models#43]
Error log:
`java.lang.IllegalStateException: Internal error: Unexpected failure when preparing tensor allocations: tensorflow/lite/kernels/conv.cc:224 input->dims->size != 4 (1 != 4)Node number 0 (CONV_2D) failed to prepare.`

with the simple custom keras model the interpreter doesn't give any error 
but with the style_transfer tflite model gives the above error 

Any idea ?

Thank you in advance

**Comment by jamesonthecrow** [comment]
Hi, sorry you're experiencing this issue. I have a couple of questions to help troubleshoot.

1. Which tool did you use to create your style transfer model?
2. When you get this error, are you using the [FritzVisionStylePredictor](https://docs.fritz.ai/android/3.6.8/reference/ai/fritz/vision/styletransfer/FritzVisionStylePredictor.html)

**Comment by Jayanth-L** [comment]
(1) I tranied the model myself with the coco dataset and used the default TFLiteConverter to convert keras model to tflite model
(2) Nope i didn't use fritz sdk, just used the tensorflow lite library from jcenter.
here is the code


`var tensorflowInterpreter = Interpreter(File(filesDir, "model.tflite"))
tensorflowInterpreter.run(floatArrayStyle, resultDataStyle)`

**Comment by hsiaoer** [comment]
Can you add how floatArrayStyle and resultDataStyle are defined? It looks like the dimensions of the input / output are off.

**Comment by jamesonthecrow** [comment]
Also, did you train and convert the model with the code in this `fritz-models` repository?

**Comment by Jayanth-L** [comment]
yes,
the inputs and outputs are:
`val resultDataStyle = ByteBuffer.allocateDirect(4 * STYLE_PAINT_HEIGHT * STYLE_PAINT_WIDTH * 3)
var floatArrayStyle: FloatArray = FloatArray(STYLE_PAINT_HEIGHT * STYLE_PAINT_WIDTH * 3 * 4)`

yes i tried with converting the keras model and also with the frozen_graph method in the repo, both of them gave same error
and also i tried with the starry_night model in the example, no success same error.

**Comment by hsiaoer** [comment]
Your input is a byte buffer, so it makes sense to multiply it by 4 (4 bytes per float). Your output is a FloatArray format so you don't need to include the * 4. I'd suggest making them both byte buffers however:

```
inputByteBuffer = ByteBuffer.allocateDirect(4 * height * width * NUM_CHANNELS);
inputByteBuffer.order(ByteOrder.nativeOrder());

outputByteBuffer = ByteBuffer.allocateDirect(4 * height * width * NUM_CHANNELS);
outputByteBuffer.order(ByteOrder.nativeOrder());
```
Where num channels = 3, height = 400, width = 300.

**Comment by Jayanth-L** [comment]
> Your input is a byte buffer, so it makes sense to multiply it by 4 (4 bytes per float). Your output is a FloatArray format so you don't need to include the * 4. I'd suggest making them both byte buffers however:
> 
> ```
> inputByteBuffer = ByteBuffer.allocateDirect(4 * height * width * NUM_CHANNELS);
> inputByteBuffer.order(ByteOrder.nativeOrder());
> 
> outputByteBuffer = ByteBuffer.allocateDirect(4 * height * width * NUM_CHANNELS);
> outputByteBuffer.order(ByteOrder.nativeOrder());
> ```
> 
> Where num channels = 3, height = 400, width = 300.

Thank you very much  @hsiaoer 
this has indeed solved my problem
yes the problem was with the right dimensions for input and output

Once again thank you very much :)

Shall i close the issue ?

**Comment by hsiaoer** [comment]
Great! Glad that worked. I'll mark this issue as resolved.
