### ISSUE TITLE
I wanna just know the licensing status of the style images ?

### ISSUE THREAD

**Issue by Jayanth-L** [fritzlabs/fritz-models#45]
I wanna just know the licensing status of the style images ?
Like notre_dame.jpg, starry_night.jpg etc

**Comment by jamesonthecrow** [comment]
Style images for pre-trained models of paintings were obtained from sources such as the [Wikimedia Commons](https://en.wikipedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg#filelinks). Modern images such as Notre Dame were taken from [Unsplash](https://unsplash.com/), a fantastic resource for free usable images.
