### ISSUE TITLE
 image_stylization train parameters

### ISSUE THREAD

**Issue by LeenluTo** [fritzlabs/fritz-models#47]
thanks for your share!
How do I set weights and epoch when I train own personal style transfer model? I use the default parameters training on coco data set, but the inference result have some small  black or white block.

**Comment by jamesonthecrow** [comment]
You can use a pre-trained checkpoint for training by providing a path to an h5 file to the `--fine-tune-checkpoint` argument during training. The model will train from `--num-iterations` (or steps) where an iteration is a single batch. Depending on the size of your dataset, you can compute the number of epochs by computing `epochs = <number of images in your dataset> / (num_iterations * batch_size)`. In general, we find that it takes roughly 20,000 iterations with a batch_size of 24 to train a model from scratch.

You may need to adjust style and content weights to see good results depending on your style image. Also, make sure that your style image is an RGB image (no alpha channel and not greyscale).
