### ISSUE TITLE
update slack invite link

### ISSUE THREAD

**Issue by erwanp** [fritzlabs/fritz-models#52]
Hello, 

The [Slack invite link](https://fritz-ai-community.slack.com/join/shared_invite/enQtNTI4MDcxMzI1MzAwLWIyMjRmMGYxYjUwZmE3MzA0MWQ0NDk0YjA2NzE3M2FjM2Y5MjQxMWM2MmQ4ZTdjNjViYjM3NDE0OWQxOTBmZWI) on the Readme.md has expired. 

Erwan

**Comment by jamesonthecrow** [comment]
Thank you for bringing this to our attention. We'll be updating the link shortly, but in the mean time, this should work:

https://join.slack.com/t/fritz-ai-community/shared_invite/enQtNTY5NDM2MTQwMTgwLWU4ZDEwNTAxYWE2YjIxZDllMTcxMWE4MGFhNDk5Y2QwNTcxYzEyNWZmZWEwMzE4NTFkOWY2NTM0OGQwYjM5Y2U
