### ISSUE TITLE
Does the image-segmentation model only train one image?

### ISSUE THREAD

**Issue by randylu** [fritzlabs/fritz-models#62]
I just look through the image segmentation model, and have an question about the file train.py(https://github.com/fritzlabs/fritz-models/blob/master/image_segmentation/image_segmentation/train.py), it seems that only one image is used to train the model, the code is pasted out.

---------------------------------------------------------------- 
```
def _prepare_dataset(args, n_classes):
    dataset = ADE20KDatasetBuilder.build(
        args.data,
        n_classes=n_classes,
        batch_size=args.batch_size,
        image_size=(args.image_size, args.image_size),
        augment_images=False,
        parallel_calls=args.parallel_calls,
        prefetch=True,
    )

    iterator = dataset.make_one_shot_iterator()
    example = iterator.get_next()

    return {           # Here, just return only one image, am i right?
        'input': example['image'],
        'mask_4': example['mask_4'],
        'mask_8': example['mask_8'],
        'mask_16': example['mask_16'],
    }
```
----------------------------------------------------------------

**Comment by jamesonthecrow** [comment]
No. The return value is a tensor containing a batch of images. The data for each image in the dataset is fed to that tensor during training.
